channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==5.9.8
  - scikit-learn==1.3.2
  - scipy==1.10.1
  - xgboost==1.7.6
name: mlflow-env
