name: Create Package
description: create package on the private pypi repository
runs:
  using: "composite"
  steps:
    - name: set git config
      run: git config user.name GithubAction  && git config user.email mlcubedevteam@gmail.com
      shell: bash
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.1
        virtualenvs-create: false
        installer-parallel: true
    - name: add private pypi
      run: make add-private-pypi
      shell: bash
    - name: setup environment
      run: make minimum-requirements && poetry run pip install --upgrade -r requirements.txt --trusted-host pypi.mlcube.com
      shell: bash
    - name: create version and publish
      run: make version
      shell: bash
